services:
  app:
    image: alpercitak/nest-pnpm-docker
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000

  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    ports:
      - 9000:8080

  consul:
    image: consul
    command: agent -server -bootstrap -ui -client="0.0.0.0"
    ports:
      - 8500:8500
      - 8600:8600/udp
